language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
after_success:
- mvn -P coverall clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: r1xMho4xp6d3UTVeRetxfYYYJHPFIyUX/piwyOIIVWmp5xsRQjnoNCZwJw3xEcQ/Q6IVhbXEJhH85b5pRppe+otsu3TdQ3GQvgC991C6Xw38vvcTgrkyjeRnlFTf/HhgrE9kgKZOLdlKFjQJqJOgd62nobIVG/qmCK6T4g2OgZcQTPOIgIErzO5rctWRdJHJ4ELrDzHP6lqK4noAU3DM6WaazUvk7EU3pt/nbcK+tdGjCsIMyNFnzYNBK6Mk5dgg3KwSEll8p3MiK2kZ0WASL/F++dUl0wrfvhq15K78J929S8MklMHlbmnA+UXVbi0dAfu57NAwoCGU4krYJRmwQh5iP1J0ruPs2lWRmd2MIVuOPe3Pt1Kx0OtydTSzXHXw3riNtwD9DdujQbb2laJB+NEgNsVEgRhPGeDGdseFfcKKcSLZUVgx3zYE3/pMrdcKQNtoMzrgI3NE92sbNbTxW5AzdGmYS41L16JlfPFvFUeeivqNM6MZSdcdLsY6zrMAj40SMSJfVUOHaUJQSkQO034i/bDEOhA3pAIxO23cEr6ITR4w0zTNM0Uq/yl1N9LogdpjZppvD87guCivsVqnUB2PJ7/KidlOkf8aUsJBl3FdGZcDkkCRWj0E3XtfJxTWz190aA/Q3sUP+FAGkiZ7dQfwwwcKaEgBf3R5a7+gnJk=
